name: reproduce-chexnet
channels:
  - conda-forge
dependencies:
  - python = 3.6.5
  - numpy
  - matplotlib
  - pillow
  - pandas
  - scikit-image
  - scikit-learn
  - seaborn
  - jupyterlab
  - ipykernel