name: reproduce-chexnet-covid
channels:
  - conda-forge
dependencies:
  - python = 3.8
  - numpy
  - matplotlib
  - pillow = 5.1.0
  - pandas
  - scikit-image
  - scikit-learn
  - seaborn
  - jupyterlab
  - ipykernel = 4.8.2
